// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using SandubaApi.Context;

#nullable disable

namespace SandubaApi.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20231011173802_MigracaoInicial")]
    partial class MigracaoInicial
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.12")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            modelBuilder.Entity("SandubaApi.Models.Categoria", b =>
                {
                    b.Property<int>("CategoriaId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.HasKey("CategoriaId");

                    b.ToTable("Categorias");
                });

            modelBuilder.Entity("SandubaApi.Models.Ingrediente", b =>
                {
                    b.Property<int>("IngredienteId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<int>("CategoriaId")
                        .HasColumnType("int");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<int>("Quantidade")
                        .HasColumnType("int");

                    b.Property<int?>("SanduicheId")
                        .HasColumnType("int");

                    b.HasKey("IngredienteId");

                    b.HasIndex("CategoriaId");

                    b.HasIndex("SanduicheId");

                    b.ToTable("Ingredientes");
                });

            modelBuilder.Entity("SandubaApi.Models.Sanduiche", b =>
                {
                    b.Property<int>("SanduicheId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<string>("Descricao")
                        .HasColumnType("longtext");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.HasKey("SanduicheId");

                    b.ToTable("Sanduiches");
                });

            modelBuilder.Entity("SandubaApi.Models.Ingrediente", b =>
                {
                    b.HasOne("SandubaApi.Models.Categoria", "Categoria")
                        .WithMany("Ingredientes")
                        .HasForeignKey("CategoriaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("SandubaApi.Models.Sanduiche", null)
                        .WithMany("Ingredientes")
                        .HasForeignKey("SanduicheId");

                    b.Navigation("Categoria");
                });

            modelBuilder.Entity("SandubaApi.Models.Categoria", b =>
                {
                    b.Navigation("Ingredientes");
                });

            modelBuilder.Entity("SandubaApi.Models.Sanduiche", b =>
                {
                    b.Navigation("Ingredientes");
                });
#pragma warning restore 612, 618
        }
    }
}
